# Generated by Django 5.1.1 on 2024-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'B.C.A'), ('MCA', 'M.C.A'), ('MSC', 'M.Sc(C.S & D.F)')], max_length=50)),
                ('semester', models.IntegerField()),
                ('week', models.IntegerField()),
                ('problemNumber', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/static/images/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'semester', 'week', 'problemNumber'), name='unique_problem')],
            },
        ),
    ]
