# Generated by Django 5.1.1 on 2024-10-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_image'),
        ('students', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekcommit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
