# Generated by Django 5.1.1 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_weekcommit_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcompletion',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
