# Generated by Django 5.1.1 on 2025-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problemcompletion_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcompletion',
            name='instructor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
