# Generated by Django 5.1.1 on 2024-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
