# Generated by Django 5.1.1 on 2024-10-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=15)),
                ('week', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculty Activities',
            },
        ),
        migrations.CreateModel(
            name='LastDateOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'B.C.A'), ('MCA', 'M.C.A'), ('MSC', 'M.Sc(C.S & D.F)')], max_length=15)),
                ('semester', models.IntegerField()),
                ('week', models.IntegerField()),
                ('last_date', models.DateField()),
            ],
            options={
                'unique_together': {('course', 'semester', 'week')},
            },
        ),
    ]
