# Generated by Django 5.1.1 on 2024-10-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('faculty', '0004_alter_faculty_groups_alter_faculty_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted ', related_name='faculty_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='faculty_user_permissions', to='auth.permission', verbose_name='user_permissions'),
        ),
    ]
