# Generated by Django 5.1.1 on 2025-04-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_codesubmission_instructoractionlog_instructorcomment_and_more'),
        ('problems', '0004_alter_weekcommit_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.problemcompletion')),
            ],
        ),
    ]
